# **ICT303 - Advanced Machine Learning and Artificial Intelligence**
# **Lab 1 - Introduction to Python, NumPy and Torch**

The purpose of this lab is to provide you with the Python toolkit you will be using in this unit. This includes:
- Familiarize yourself with Python programming. Although there is no unit within the IT degree that explicitly teaches Python, as an IT student of Murdoch, you should by now have learned C, Java and eventually C++. These are the foundations that will enable you to learn any other programming language by your own. In fact,  as an IT expert, you MUST learn how to learn by yourself.
- Familiarize yourself with some important Python libraries that we will be using during the semester. These include NumPy and PyTorch.

Note that, Section 2 of this lab has been adapted from https://numpy.org/doc/stable/user/quickstart.html. Sections 3 onwards have been adapted from https://deeplearning.cs.cmu.edu/F20/index.html.

### **1. Python**

In this unit, we will use the [*Colab research platform*](https://colab.research.google.com/) for programming. Since you are reading this, it means you have already created a Google account and managed to open this Colab notebook.

Before you continue, I recommend to create a folder named ICT303 in your Google drive, and make sure you save all your work (i.e., the notebooks and associated files your will create as part of this unit) in it.

You can find more information on how to use Colab and its features in the link above. Note also that Colab integrates cleanly with Github, allowing both loading notebooks from Github and saving notebooks into Github. You can find more details here: https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb.

Once done, it is time for you to learn a little bit about Python. There are plenty of online resources that you can use. I recommend downloading this tutorial notebook from CMU: https://deeplearning.cs.cmu.edu/F20/document/recitation/Rec_0A_Fundamentals_of_Python.zip
- Download the notebook and then upload it to your google drive and view it in Colab.
- Work through the tutorial step by step.

Note that you do not need to do the entire Python tutorial. Scheme through it and try to:
- Understand the structure of a Python program
- How to create classes, methods and functions
- How to pass in parameters into functions.

Then, use this tutorial as a reference whenever  you need to create something with Python.


### **2. NumPy**

The first library of interest is [NumPy](http://www.numpy.org/). You can find more details about NumPy at https://numpy.org/doc/stable/user/quickstart.html. Here, I will just summarize some important aspects. You can also go through this CMU tutorial: https://deeplearning.cs.cmu.edu/F20/document/recitation/Rec_0B_Fundamentals_of_Numpy.zip

In this document, I will summarize some of the most important features of NumPy.

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- A powerful N-dimensional array object
- Sophisticated (broadcasting) functions
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

#### **2.1. The Basics**

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called **axes**.

NumPy arrays are called **ndarray** defiied in the package **numpy.array**.

****Example 1 - A point or vector in 3D space:****
A point in 3D space has 3 coordinates (x, y, z). Similarly, a vector in 3D space has 3 coordinates (x, y, z). Thus, from the programming point of view, they can both be defined using an array of 3 elements. Using NumPy **ndarray**, they can be defined as an array that has one axis (one dimension). For example:

In [ ]:
## A point in 3D space
p = [1, 2, 1]

## A vector in 3D space
v = [3, 2.1, 5]

## printing
print("The point is: ")
print(p)
print("The vector is: ")
print(v)

The point is: 
[1, 2, 1]
The vector is: 
[3, 2.1, 5]


***Example 2 - A list of 3D points***

Assume that we would like to create a data structure that will hold a list of 3D points.  Using NumPy's **ndarray**, it can be defined using an array that has two axes:



In [ ]:
import numpy as np
vertices =np.array([[1, 0, 0],
           [3, 2, 0.1],
           [-1.3, 2.4, 5],
           [5.3, 3, -2.3]])
# Printing - method 1
print(vertices)

# Printing - method 2
vertices

# Printing the first point or row (of index 0)
vertices[0,]

# Printing the first column (of index 0)
vertices[:,0]


[[ 1.   0.   0. ]
 [ 3.   2.   0.1]
 [-1.3  2.4  5. ]
 [ 5.3  3.  -2.3]]


array([ 1. ,  3. , -1.3,  5.3])

This ndarray has two axes. The first axis has a length of 4. The second axis has a length of 3.

The class ndarray has many important attributes. The most important ones include:

- ***ndarray.ndim*** - The number of axes (dimensions) of the array.

- ***ndarray.shape*** - the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

- ***ndarray.size*** - the total number of elements of the array. This is equal to the product of the elements of shape.

- ***ndarray.dtype*** - an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

- ***ndarray.itemsize*** - the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

- ***ndarray.data*** - the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

***Example 3.***  Try these properties on the examples defined above.

#### **2.2. Creating and printing NumPy arrays**

Please refer to Sections ***Array Creation*** and ***Printing Arrays*** of https://numpy.org/doc/stable/user/quickstart.html

***Example 4***: Create a random 1D array of size $32$. Then try to:
- Reshape the 1D array into a 2D array of size $8 \times 4$ (i.e., axes 1 will have size $8$ while axes $2$ will have size $4$). Use the function numpy.arrange. For this, please refer to https://numpy.org/doc/stable/reference/generated/numpy.reshape.html
- Display (print) the results.

As a bonus question, try to rearrange the 2D array into a 1D array. For this, check the different parameters of the function reshape, especially the last parameter which takes one of the three values: 'C', 'F', and 'A'. Please refer to https://numpy.org/doc/stable/reference/generated/numpy.reshape.html.

***Solution to Example 4***
For this, we will use the function numpy.random.rand, which creates an array of a given shape and populates it with random samples from a uniform distribution over $[0, 1)$. If you want the values to be between $a$ and $b$ value (with $a \le b$), then you have to multiply the generated values by $(b - a)$ and then add $a$.

In [ ]:
## Example 4 - Creating a 1D array of size 32. The values will be set randomly
import numpy as np
from numpy import random

# defining the parameters
a = 0
b = 100
n = 32

# Creating the random array
values = random.rand(32)
values = values * (b - a) + a

values  # uncomment this if you would like to print

array([65.70722598, 84.01224986, 89.86851075, 23.29652613, 13.33548868,
       86.82806946, 34.96298169, 73.50447515, 93.94145887, 65.68474251,
        8.12162797, 71.30407915, 96.38174419, 75.54278515, 84.14742831,
       94.42323062, 28.56379293, 31.01575462, 45.13472836, 16.77971794,
       62.52221272,  8.9797287 , 64.75901689, 15.03968071, 33.7477485 ,
       34.36183157, 93.73315973, 47.26393328, 17.40858504, 25.15098279,
       79.25263853, 43.80198395])

In [ ]:
# Rearrange the 2D array into a 2D arrat of size 8 x 4
values = np.reshape(values, [8, 4], 'C')

values

array([[65.70722598, 84.01224986, 89.86851075, 23.29652613],
       [13.33548868, 86.82806946, 34.96298169, 73.50447515],
       [93.94145887, 65.68474251,  8.12162797, 71.30407915],
       [96.38174419, 75.54278515, 84.14742831, 94.42323062],
       [28.56379293, 31.01575462, 45.13472836, 16.77971794],
       [62.52221272,  8.9797287 , 64.75901689, 15.03968071],
       [33.7477485 , 34.36183157, 93.73315973, 47.26393328],
       [17.40858504, 25.15098279, 79.25263853, 43.80198395]])

#### **2.3. Basic Operations**

You can do arithmetic operations (addition, subtraction, multiplication) on NumPy arrays. These will be applied element wise. For example, to add two arrays ***A*** and ****B***  of same dimension, you do not need to write a loop through its elements, you just need to write ***A+B***. Please refer to the section ***Basic Operations*** of https://numpy.org/doc/stable/user/quickstart.html.

It is important to pay attention to some aspects that are specific to NumPy arrays. In particular, the product operator *  operates elementwise in NumPy array. If you want to use matric product, then you have t yse the operator ***@*** (in Python > 3.5) or the ***dot*** function. Please refer to https://numpy.org/doc/stable/user/quickstart.html for more details. The example below illustrates this concept.

In [ ]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
C1 = A * B     # elementwise product

C2 = A @ B     # matrix product

C3 = A.dot(B)  # another matrix product

Note also that the NumPy array class provides methods such as sum, min, max, etc., which operate on the entire elements of the array. By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:



In [ ]:
b = np.arange(12).reshape(3, 4)
print(b)                 # Printing b

display(b.sum(axis=0))     # sum of each column

b.min(axis=1)     # min of each row

b.cumsum(axis=1)  # cumulative sum along each row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

NumPy also provides common mathematical functions such as $\text{exp}$ (for exponential), $\text{sqrt}$ (for square root), etc.

#### **2.4. Indexing, Slicing and Iterating**

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.



In [ ]:
# An array of 10 elements with values [0, 1, , ..., 9] and make every element power 3
a = np.arange(10)
a

# First element
print("First element: ")
a[0]

# Last element
print("Last element: ")
a[-1]

# Print the 3rd element - Similar to C, array indices in NumPy start from 0
print("3rd element: ")
a[2]

# Print the elements index between 2 and 5
print("Elements from 2 to 5: ")
a[2:5]

# From start to position 6, exclusive, set every 2nd element to 1000
# This is equivalent to a[0:6:2] = 1000;
a[:6:2] = 1000
a

# Reverse the array a, i.e., last element becomes first, etc.
a[::-1]

# Looping through the elements of a
for x in a:
    print(x)

First element: 
Last element: 
3rd element: 
Elements from 2 to 5: 
1000
1
1000
3
1000
5
6
7
8
9


**Multidimensional** arrays can have one index per axis. These indices are given in a tuple separated by commas.

When fewer indices are provided than the number of axes, the missing indices are considered complete slices. For instance, in the example below, b[1] is the same as b[1, :] and is also the same as b[1, ...] where the three dots mean the remaining dimensions.

In [ ]:
import numpy as np

b = np.array([[ 0,  1,  2,  3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])

print(b[1])



[10 11 12 13]


In [ ]:
# Same command but written different
print(b[1,:])



[10 11 12 13]


In [ ]:
# And another way of doing the same thing
print(b[1, ...])

[10 11 12 13]


**Iterating** over multidimensional arrays is done with respect to the first axis:

In [ ]:
# Iterating over rows
for row in b:
    print(row)


[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In the example above, if $b$ had three axes (dimensions) then row will have two dimensions.

#### **2.5. Shape manipulation**

The shape of an array is the number of elements it has along each axis. You can change this shape by
- flattening it (e.g., 2D array  becomes one long 1D array) using the method **ravel()**
- reshape it. For example, if you have an array of 3 rows and 4 columns,  you can reshape it into an array of 6 rows and 2 columns using the method **reshape()**.



#### **2.6. Other matters**

You can stack together several arrays along different axis to form a new array. You can also split one array into several smaller ones.

It also important to pay attention to how arrays are copied. Copying an array variabe into another variable can be done in different ways:
- A simple assignment $b = a$ does not make a separate (new) copy of a. Instead, $b$ becomes a new name for the same ndarray.
- Viewer or shallow copy using the view method which creates a new array that looks at the same date. Also, slicing an array returns a view of it.
- Deep copy using the method copy().



#### **2.7. Additional Reading**

For further reading, please refer to https://numpy.org/doc/stable/user/quickstart.html for more advanced topics related to NumPy arrays, including tricks and tips!

### **3. PyTorch**

The second library of interest is PyTorch, which is an open-source deep learning library for python, and will be extensively used throughout the unit. You can install PyTorch on your local machine by referring to https://PyTorch.org/get-started/locally/.

PyTorch is an open source deep learning platform that provides a seamless path from research prototyping to production deployment.
> - *Hybrid Front-End:* A new hybrid front-end seamlessly transitions between eager mode and graph mode to provide both flexibility and speed.
> - *Distributed Training:* Scalable distributed training and performance optimization in research and production is enabled by the torch.distributed backend.
> - *Python-First:* Deep integration into Python allows popular libraries and packages to be used for easily writing neural network layers in Python.
> - *Tools & Libraries:* A rich ecosystem of tools and libraries extends PyTorch and supports development in computer vision, NLP and more.
>
> To learn more about PyTorch and expand your knowledge, please refer to [About PyTorch](https://pytorch.org/)*

One consideration as to why we are using PyTorch is most succinctly summerized by Andrej Karpathy, Director of Artificial Intelligence and Autopilot Vision at Tesla. The technical summary can be found [here](https://twitter.com/karpathy/status/868178954032513024?lang=en).

To use PyTorch in colab, please refer to https://colab.research.google.com/github/omarsar/pytorch_notebooks/blob/master/pytorch_quick_start.ipynb.

You can use the code below to check whether PyTorch is properly installed and which version is installed.

In [ ]:
## Checking that PyTorch is running

import torch

# Check the version
print(torch.__version__)

2.5.1+cu124


In [ ]:
# Creare a simple Tensor
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

One of the fundamental concepts in PyTorch is the **Tensor**, a multi-dimensional matrix containing elements of a single type. Tensors are similar to NumPy nd-arrays. They also support most of the functionality that NumPy matrices do.

Please go through this guide: https://pytorch.org/tutorials/ to learn about PyTorch, from the basics to advanced topics. Many of the examples are about deep learning - don't worry about them at this stage. Below are the topics that you need to familiarize yourself with at this stage.

Start by familiarizing yourself with ***the basics*** at: https://pytorch.org/tutorials/beginner/basics/intro.html. You should learn about:
- **Tensors:** These are a specialized data structure, very similar to arrays and matrices. Tensors in PyTorch are used to encode inputs and outputs of a model (neural network), as well as the model's parameters. They are similar to NumPy's ndarrays, except that tensors can run on GPUs or other hardware accelerators.  In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data.
- **Datasets and DataLoaders:** PyTorch offers ready-to-use classes and functions for loading standard datasets used to train neural networks.

The Quick Start section of the tutorial above provides a quick overview of the functionalities available

Once we advance in the unit and you learn about neural networks, then you need to familiarize yourself with the following topics:
- **Transforms:** i.e., how to transform the data to make it suitable for training neural neytworks.
- **Build model:** to build neural network models.
- **Automatic differentiation:** I will talk about this later in the lecture.
- **Optimization loop:** I will talk about this later in the lecture.

This week, make sure that you familiarize yourself with **Tensors**. You need to know:
- How to create tensors directly from data, from another NumPy array, and from another Tensor.
- Attributes of a Tensor.
- Operations on Tensors, including indexing and slicing.

### **4. Practice what you learned**

In following exercises, you will familiarize yourself with tensors and more importantly, the PyTorch documentation. It is important to note that for this section, we are simply using PyTorch’s tensors as a matrix library, just like NumPy. So please do not use functions in torch.nn, like torch.nn.ReLU.

In PyTorch, it is very simple to convert between numpy arrays and tensors. PyTorch’s tensor library provides functions to perform the conversion in either direction.

#### **4.1. Converting from NumPy to PyTorch Tensor**
In this task, you will implement a conversion function from arrays to tensors.

The function should take a numpy ndarray and convert it to a PyTorch tensor.

*Function torch.tensor is one of the simple ways to implement it.*

**Your Task**: Implement the function `numpy2tensor`.

In [ ]:
def numpy2tensor(x):
    """
    Creates a torch.Tensor from a numpy.ndarray.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    torch.Tensor: 1-dimensional torch tensor.
    """
    # Solution
    return torch.tensor(x)

**Test Example:**

In [ ]:
import torch
import numpy as np

In [ ]:


X = np.random.randint(-1000, 1000, size=3000)

newX = numpy2tensor(X)

# printing the type of the data
print(type(newX))

# printing the data
print(newX)

<class 'torch.Tensor'>
tensor([ 115, -133,  855,  ..., -479,  710,  112])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> type(numpy2tensor(X)) </b></tt></td>
        <td style="text-align:left;"><tt> &lt;class &#39;torch.Tensor&#39;&gt; </tt></td>
    </tr>
</table>

#### **4.2. Converting from PyTorch Tensor to NumPy**

In this task, you will implement a conversion function from tensors to arrays.

The function should take a PyTorch tensor and convert it to a numpy ndarray.

**Your Task**: Implement the function `tensor2numpy`.

In [ ]:
def tensor2numpy(x):
    """
    Creates a numpy.ndarray from a torch.Tensor.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    numpy.ndarray: 1-dimensional numpy array.
    """

    # Solution
    return x.numpy()

**Test Example:**

In [ ]:
X = np.random.randint(-1000, 1000, size=3000)
X = torch.from_numpy(X)

print(type(tensor2numpy(X)))

<class 'numpy.ndarray'>


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> type(tensor2numpy(X)) </b></tt></td>
        <td style="text-align:left;"><tt> &lt;class &#39;numpy.ndarray&#39;&gt; </tt></td>
    </tr>
</table>

### **5. Vectorization**

Lists are a foundational data structure in Python, allowing us to create simple and complex algorithms to solve problems. However, in mathematics and particularly in linear algebra, we work with vectors and matrices to model problems and create statistical solutions. Through these exercises, we will begin introducing you to how to think more mathematically through the use of NumPy by starting with a process known as vectorization.

Index chasing is a very valuable skill, and certainly one you will need in this course, but mathematical problems often have simpler and more efficient representations that use vectors. The process of converting from an implementation that uses indicies to one that uses vectors is known as vectorization. Once vectorized, the resulting implementation often yields to a faster and more readable code than before.

In the following problems, we will ask you to practice reading mathematical expressions and deduce their vectorized equivalent along with their implementation in Python. You will use the NumPy array object as the Python equivalent to a vector, and in later sections you will work with sets of vectors known as matrices.

For the following tasks you will be asked to complete the same task first using **NumPy** Operations, then again using **Torch** Operations.

#### **5.1. Dot Product**

In this task, you will implement the dot product function for numpy arrays & torch tensors.

The dot product (also known as the scalar product or inner product) is the linear combination of the n real components of two vectors.

$$x \cdot y = x_1 y_1 + x_2 y_2 + \cdots + x_n y_n$$

**Your Task**: Implement the functions `NUMPY_dot` & `PYTORCH_dot`.

In [ ]:
def EXAMPLE_inefficient_dot(x, y):
    """
    Inefficient dot product of two arrays.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.int64: scalar quantity.
    """
    assert(len(x) == len(y))

    result = 0
    for i in range(len(x)):
        result += x[i]*y[i]

    return result

In [ ]:
def NUMPY_dot(x, y):
    """
    Dot product of two arrays.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.int64: scalar quantity.
    """
    # Here we will do element wise multiplication
    T = np.multiply(x, y)
    # Sum the elements of T and return the,
    return T.sum()

In [ ]:
def PYTORCH_dot(x, y):
    """
    Dot product of two tensors.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.int64: scalar quantity.
    """
    # Here we will do element wise multiplication
    T = np.multiply(x, y)

    # Sum the elements of T and return the,
    return T.sum()


**Test Example:**

In [ ]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=3000)
Y = np.random.randint(-1000, 1000, size=3000)


print(NUMPY_dot(X,Y))

X = torch.from_numpy(X)
Y = torch.from_numpy(Y)
print(PYTORCH_dot(X,Y))


7082791
tensor(7082791)


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> NUMPY_dot(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt> 7082791 </tt></td>
        <td style="text-align:left;"><tt><b> PYTORCH_dot(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt> 7082791 </tt></td>
    </tr>
</table>

#### **5.2. Outer Product**

In this task, you will implement the outer product function for numpy arrays & torch tensors.

The outer product (also known as the tensor product) of vectors x and y is defined as

$$
x \otimes y =
\begin{bmatrix}
x_1 y_1 & x_1 y_2 & … & x_1 y_n\\
x_2 y_1 & x_2 y_2 & … & x_2 y_n\\
⋮ & ⋮ & ⋱ & ⋮ \\
x_m y_1 & x_m y_2 & … & x_m y_n
\end{bmatrix}
$$

**Your Task**: Implement the functions `NUMPY_outer` & `PYTORCH_outer`.


In [ ]:
def EXAMPLE_inefficient_outer(x, y):
    """
    Inefficiently compute the outer product of two vectors.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """
    result = np.zeros((len(x), len(y)))
    for i in range(len(x)):
        for j in range(len(y)):
            result[i, j] = x[i]*y[j]

    return result

In [ ]:
def NUMPY_outer(x, y):
    """
    Compute the outer product of two vectors.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """

    new_x = x.reshape(len(x), 1)

    return new_x * y
    """
    n = len(x)    # length of x
    m = len(y)    # length of y
    # 1. Make x a column vector and replicate it m times
    new_x = np.tile(x,  (m, 1) )
    # 2. Make y a row vector (which it is already) and replicate it n times
    new_y = np.tile(y,  (n, 1) )

    # 3. Do element wise
    res = np.multiply( new_x.transpose(), new_y)

    return res
    """

In [ ]:
def PYTORCH_outer(x, y):
    """
    Compute the outer product of two vectors.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.Tensor: 2-dimensional torch tensor.
    """

    new_x = x.reshape(len(x), 1)

    return new_x * y

    # return NotImplemented

**Test Example:**

In [ ]:
np.random.seed(0)

# NumPy Version
X = np.random.randint(-1000, 1000, size=3) #000)
Y = np.random.randint(-1000, 1000, size=5)# 000)
Z = NUMPY_outer(X,Y)

print("NumPy Result:")
print(Z)

# PyTorch Version
X = torch.from_numpy(X)
Y = torch.from_numpy(Y)
print("PyTorch Result:")
print(PYTORCH_outer(X,Y))


NumPy Result:
[[ -68256   52140   74892 -230996 -121028]
 [ -95256   72765  104517 -322371 -168903]
 [ 141048 -107745 -154761  477343  250099]]
PyTorch Result:
tensor([[ -68256,   52140,   74892, -230996, -121028],
        [ -95256,   72765,  104517, -322371, -168903],
        [ 141048, -107745, -154761,  477343,  250099]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> NUMPY_outer(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[&nbsp;&nbsp;59092&nbsp;-144096&nbsp;&nbsp;136512&nbsp;...&nbsp;&nbsp;-53088&nbsp;&nbsp;-86268&nbsp;&nbsp;&nbsp;53404] <br>
            &nbsp;[&nbsp;&nbsp;82467&nbsp;-201096&nbsp;&nbsp;190512&nbsp;...&nbsp;&nbsp;-74088&nbsp;-120393&nbsp;&nbsp;&nbsp;74529] <br>
            &nbsp;[-122111&nbsp;&nbsp;297768&nbsp;-282096&nbsp;...&nbsp;&nbsp;109704&nbsp;&nbsp;178269&nbsp;-110357] <br>
            &nbsp;... <br>
            &nbsp;[-144551&nbsp;&nbsp;352488&nbsp;-333936&nbsp;...&nbsp;&nbsp;129864&nbsp;&nbsp;211029&nbsp;-130637] <br>
            &nbsp;[-179707&nbsp;&nbsp;438216&nbsp;-415152&nbsp;...&nbsp;&nbsp;161448&nbsp;&nbsp;262353&nbsp;-162409] <br>
            &nbsp;[&nbsp;&nbsp;88825&nbsp;-216600&nbsp;&nbsp;205200&nbsp;...&nbsp;&nbsp;-79800&nbsp;-129675&nbsp;&nbsp;&nbsp;80275]] <br>
        </tt></td>
        <td style="text-align:left;"><tt><b> PYTORCH_outer(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[&nbsp;&nbsp;59092&nbsp;-144096&nbsp;&nbsp;136512&nbsp;...&nbsp;&nbsp;-53088&nbsp;&nbsp;-86268&nbsp;&nbsp;&nbsp;53404] <br>
            &nbsp;[&nbsp;&nbsp;82467&nbsp;-201096&nbsp;&nbsp;190512&nbsp;...&nbsp;&nbsp;-74088&nbsp;-120393&nbsp;&nbsp;&nbsp;74529] <br>
            &nbsp;[-122111&nbsp;&nbsp;297768&nbsp;-282096&nbsp;...&nbsp;&nbsp;109704&nbsp;&nbsp;178269&nbsp;-110357] <br>
            &nbsp;... <br>
            &nbsp;[-144551&nbsp;&nbsp;352488&nbsp;-333936&nbsp;...&nbsp;&nbsp;129864&nbsp;&nbsp;211029&nbsp;-130637] <br>
            &nbsp;[-179707&nbsp;&nbsp;438216&nbsp;-415152&nbsp;...&nbsp;&nbsp;161448&nbsp;&nbsp;262353&nbsp;-162409] <br>
            &nbsp;[&nbsp;&nbsp;88825&nbsp;-216600&nbsp;&nbsp;205200&nbsp;...&nbsp;&nbsp;-79800&nbsp;-129675&nbsp;&nbsp;&nbsp;80275]] <br>
        </tt></td>
    </tr>
</table>

#### **5.3. Hadamard Product**

In this task, you will implement the Hadamard product function, `multiply`, for numpy arrays & torch tensors.

The Hadamard product (also known as the Schur product or entrywise product) of vectors x and y is defined as

$$
x \circ y =
\begin{bmatrix}
x_{1} y_{1} & x_{2} y_{2} & … & x_{n} y_{n}
\end{bmatrix}
$$

**Your Task**: Implement the functions `NUMPY_multiply` & `PYTORCH_multiply`.

In [ ]:
def EXAMPLE_inefficient_multiply(x, y):
    """
    Inefficiently multiply arguments element-wise.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.ndarray: 1-dimensional numpy array.
    """
    assert(len(x) == len(y))

    result = np.zeros(len(x))
    for i in range(len(x)):
        result[i] = x[i]*y[i]

    return result

In [ ]:
def NUMPY_multiply(x, y):
    """
    Multiply arguments element-wise.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.ndarray: 1-dimensional numpy array.
    """

    return np.multiply(x, y)

In [ ]:
def PYTORCH_multiply(x, y):
    """
    Multiply arguments element-wise.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.Tensor: 1-dimensional torch tensor.
    """

    return torch.multiply(x, y)

**Test Example:**

In [ ]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=3000)
Y = np.random.randint(-1000, 1000, size=3000)

print("NumPy result:")
print(NUMPY_multiply(X,Y))


X = torch.from_numpy(X)
Y = torch.from_numpy(Y)
print("PyTorch result:")
print(PYTORCH_multiply(X,Y))


NumPy result:
[  59092 -201096 -282096 ...  129864  262353   80275]
PyTorch result:
tensor([  59092, -201096, -282096,  ...,  129864,  262353,   80275])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> NUMPY_multiply(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt>
            [&nbsp;&nbsp;59092&nbsp;-201096&nbsp;-282096&nbsp;...&nbsp;&nbsp;129864&nbsp;&nbsp;262353&nbsp;&nbsp;&nbsp;80275]
        </tt></td>
        <td style="text-align:left;"><tt><b> PYTORCH_multiply(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt>
            [&nbsp;&nbsp;59092&nbsp;-201096&nbsp;-282096&nbsp;...&nbsp;&nbsp;129864&nbsp;&nbsp;262353&nbsp;&nbsp;&nbsp;80275]
        </tt></td>
    </tr>
</table>

#### **5.4. Sum-Product**
In this task, you will implement the sum-product function for numpy arrays & torch tensors.

The sum-product of vectors x and y, each with n real component, is defined as

$$
f(x, y) =
{
\begin{bmatrix}
1\\
1\\
⋮\\
1
\end{bmatrix}^{\;T}
%
\begin{bmatrix}
x_1 y_1 & x_1 y_2 & … & x_1 y_n\\
x_2 y_1 & x_2 y_2 & … & x_2 y_n\\
⋮ & ⋮ & ⋱ & ⋮ \\
x_m y_1 & x_m y_2 & … & x_m y_n
\end{bmatrix}
%
\begin{bmatrix}
1\\
1\\
⋮\\
1
\end{bmatrix}
} =
\displaystyle\sum_{i=1}^{n} \displaystyle\sum_{j=1}^{n} x_i \cdot y_j
$$

**Your Task**: Implement the functions `NUMPY_sumproduct` & `PYTORCH_sumproduct`.


In [ ]:
def EXAMPLE_inefficient_sumproduct(x, y):
    """
    Inefficiently sum over all the dimensions of the outer product
    of two vectors.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.int64: scalar quantity.
    """
    # Check that the two lengths are correct
    assert(len(x) == len(y))

    result = 0
    for i in range(len(x)):
        for j in range(len(y)):
            result += x[i] * y[j]

    return result

In [ ]:
def NUMPY_sumproduct(x, y):
    """
    Sum over all the dimensions of the outer product of two vectors.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.int64: scalar quantity.
    """

    # Check that the two lengths are correct
    assert(len(x) == len(y))

    n = len(x)
    one   = np.ones((1, n))
    one_t = np.ones((n, 1))

    #print(one_t)

    # Use the symbol @ for matrix multiplications
    return one @ (NUMPY_outer(x, y) @ one_t)

In [ ]:
def PYTORCH_sumproduct(x, y):
    """
    Sum over all the dimensions of the outer product of two vectors.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.int64: scalar quantity.
    """

    # Check that the two lengths are correct
    assert(len(x) == len(y))

    n = len(x)
    one   = torch.ones((1, n))
    one_t = torch.ones((n, 1))

    #print(one_t)

    # Use the symbol @ for matrix multiplications
    return one @ PYTORCH_outer(x, y) @ one_t #one @ (TORCH_outer(x, y) @ one_t)

**Test Example:**

In [ ]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=3000)
Y = np.random.randint(-1000, 1000, size=3000)

print("NumPy Result: ")
print(NUMPY_sumproduct(X,Y))

X = torch.from_numpy(X)
Y = torch.from_numpy(Y)
print("PyTorch Result: ")
print(PYTORCH_sumproduct(X.float(), Y.float()))

NumPy Result: 
[[2.6542152e+08]]
PyTorch Result: 
tensor([[2.6542e+08]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> NUMPY_sumproduct(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt> 265421520 </tt></td>
        <td style="text-align:left;"><tt><b> TORCH_sumproduct(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt> 265421520 </tt></td>
    </tr>
</table>

#### **5.5. ReLU**

In this task, you will implement the ReLU activation function for numpy arrays and torch tensors.

The ReLU activation (also known as the rectifier or rectified linear unit) matrix Z resulting from applying the ReLU function to matrix X is defined such that for $X,Z \in M_{m \times n} (\mathbb{R})$,

$$Z = {\tt ReLU}(X) \implies \begin{cases}z_{ij} = x_{ij}&{\mbox{if }}x_{ij}>0\\z_{ij} = 0&{\mbox{otherwise.}}\end{cases}$$

For reference, it is common to use the notation $X = (x_{ij})$ and $Z = (z_{ij})$.

**Your Task:** Implement the functions `NUMPY_ReLU` & `PYTORCH_ReLU`.

In [ ]:
def EXAMPLE_inefficient_ReLU(x):
    """
    Inefficiently applies the rectified linear unit function
    element-wise.

    Parameters:
    x (numpy.ndarray): 2-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """
    result = np.copy(x)
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if x[i][j] < 0:
                result[i][j] = 0

    return result

In [ ]:
def NUMPY_ReLU(x):
    """
    Applies the rectified linear unit function element-wise.

    Parameters:
    x (numpy.ndarray): 2-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """

    return np.maximum(0, x)

In [ ]:
def PYTORCH_ReLU(x):
    """
    Applies the rectified linear unit function element-wise.

    Parameters:
    x (torch.Tensor): 2-dimensional torch tensor.

    Returns:
    torch.Tensor: 2-dimensional torch tensor.
    """

    return torch.maximum(torch.zeros(x.size()), x)

**Test Example:**

In [ ]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=(3000,3000))

print(NUMPY_ReLU(X))

X = torch.from_numpy(X)
print(PYTORCH_ReLU(X))



[[  0   0 653 ... 773 961   0]
 [  0 456   0 ... 168 273   0]
 [936 475   0 ... 408   0   0]
 ...
 [  0 396 457 ... 646   0   0]
 [645 943   0 ... 863   0 790]
 [641   0 379 ... 347   0   0]]
tensor([[  0.,   0., 653.,  ..., 773., 961.,   0.],
        [  0., 456.,   0.,  ..., 168., 273.,   0.],
        [936., 475.,   0.,  ..., 408.,   0.,   0.],
        ...,
        [  0., 396., 457.,  ..., 646.,   0.,   0.],
        [645., 943.,   0.,  ..., 863.,   0., 790.],
        [641.,   0., 379.,  ..., 347.,   0.,   0.]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> NUMPY_ReLU(X) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;653&nbsp;...&nbsp;773&nbsp;961&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[&nbsp;&nbsp;0&nbsp;456&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;168&nbsp;273&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[936&nbsp;475&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;408&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;... <br>
&nbsp;[&nbsp;&nbsp;0&nbsp;396&nbsp;457&nbsp;...&nbsp;646&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[645&nbsp;943&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;863&nbsp;&nbsp;&nbsp;0&nbsp;790] <br>
&nbsp;[641&nbsp;&nbsp;&nbsp;0&nbsp;379&nbsp;...&nbsp;347&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0]]
        </tt></td>
        <td style="text-align:left;"><tt><b> PYTORCH_ReLU(X) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;653&nbsp;...&nbsp;773&nbsp;961&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[&nbsp;&nbsp;0&nbsp;456&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;168&nbsp;273&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[936&nbsp;475&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;408&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;... <br>
&nbsp;[&nbsp;&nbsp;0&nbsp;396&nbsp;457&nbsp;...&nbsp;646&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[645&nbsp;943&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;863&nbsp;&nbsp;&nbsp;0&nbsp;790] <br>
&nbsp;[641&nbsp;&nbsp;&nbsp;0&nbsp;379&nbsp;...&nbsp;347&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0]]
        </tt></td>
    </tr>
</table>

#### **5.6. Prime ReLU (derivative of ReLU)**

In this task, you will implement the derivative of the ReLU activation function for numpy arrays and torch tensors.

The derivative of the ReLU activation matrix Z resulting from applying the derivative of the ReLU function to matrix X is defined such that for $X,Z \in M_{m \times n} (\mathbb{R})$,

$$Z = {\tt PrimeReLU}(X) \implies \begin{cases}z_{ij} = \frac{d}{dx_{ij}} (x_{ij}) = 1&{\mbox{if }}x_{ij}> 0\\z_{ij} = \frac{d}{dx_{ij}} (0)=0&{\mbox{otherwise.}}\end{cases}$$

For reference, it is common to use the notation $X = (x_{ij})$ and $Z = (z_{ij})$.

**Your Task:** Implement the functions `NUMPY_PrimeReLU` & `PYTORCH_PrimeReLU`.

In [ ]:
def EXAMPLE_inefficient_PrimeReLU(x):
    """
    Inefficiently applies the derivative of the rectified linear unit
    function element-wise.

    Parameters:
    x (numpy.ndarray): 2-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """

    result = np.copy(x)
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if x[i][j] <= 0:
                result[i][j] = 0
            else:
                result[i][j] = 1

    return result

In [ ]:
def NUMPY_PrimeReLU(x):
    """
    Applies the derivative of the rectified linear unit function
    element-wise.

    Parameters:
    x (numpy.ndarray): 2-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """
    y = x
    y[x<=0] = 0
    y[x>0] = 1
    return y

In [ ]:
def PYTORCH_PrimeReLU(x):
    """
    Applies derivative of the rectified linear unit function
    element-wise.

    Parameters:
    x (torch.Tensor): 2-dimensional torch tensor.

    Returns:
    torch.Tensor: 2-dimensional torch tensor.
    """

    y = x
    y[x<=0] = 0
    y[x>0] = 1
    return y

**Test Example:**

In [ ]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=(3000,3000))

# NumPy
print(NUMPY_PrimeReLU(X))

# PyTorch
X = torch.from_numpy(X)
print(PYTORCH_PrimeReLU(X))


[[0 0 1 ... 1 1 0]
 [0 1 0 ... 1 1 0]
 [1 1 0 ... 1 0 0]
 ...
 [0 1 1 ... 1 0 0]
 [1 1 0 ... 1 0 1]
 [1 0 1 ... 1 0 0]]
tensor([[0, 0, 1,  ..., 1, 1, 0],
        [0, 1, 0,  ..., 1, 1, 0],
        [1, 1, 0,  ..., 1, 0, 0],
        ...,
        [0, 1, 1,  ..., 1, 0, 0],
        [1, 1, 0,  ..., 1, 0, 1],
        [1, 0, 1,  ..., 1, 0, 0]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> NUMPY_PrimeReLU(X) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[0&nbsp;0&nbsp;1&nbsp;...&nbsp;1&nbsp;1&nbsp;0] <br>
&nbsp;[0&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;1&nbsp;0] <br>
&nbsp;[1&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;0&nbsp;0] <br>
&nbsp;... <br>
&nbsp;[0&nbsp;1&nbsp;1&nbsp;...&nbsp;1&nbsp;0&nbsp;0] <br>
&nbsp;[1&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;0&nbsp;1] <br>
&nbsp;[1&nbsp;0&nbsp;1&nbsp;...&nbsp;1&nbsp;0&nbsp;0]]
        </tt></td>
        <td style="text-align:left;"><tt><b> PYTORCH_PrimeReLU(X) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[0&nbsp;0&nbsp;1&nbsp;...&nbsp;1&nbsp;1&nbsp;0] <br>
&nbsp;[0&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;1&nbsp;0] <br>
&nbsp;[1&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;0&nbsp;0] <br>
&nbsp;... <br>
&nbsp;[0&nbsp;1&nbsp;1&nbsp;...&nbsp;1&nbsp;0&nbsp;0] <br>
&nbsp;[1&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;0&nbsp;1] <br>
&nbsp;[1&nbsp;0&nbsp;1&nbsp;...&nbsp;1&nbsp;0&nbsp;0]]
        </tt></td>
    </tr>
</table>

**Example 1 - Data*

<img src="images/ex3.png" width="600">

In [ ]:
def get_data_1():
    """
    This is the generating process from which example data 1 will derive

    Parameters:
    None

    Returns:
    numpy.ndarray: 1-d numpy array with 2-d numpy arrays as elements.
    """
    freq000 = 3; freq001 = 1; freq002 = 4; freq003 = 1
    freq010 = 5; freq011 = 9; freq012 = 2; freq013 = 6
    freq020 = 5; freq021 = 3; freq022 = 5; freq023 = 8
    frame00 = np.array([freq000, freq001, freq002, freq003])
    frame01 = np.array([freq010, freq011, freq012, freq013])
    frame02 = np.array([freq020, freq021, freq022, freq023])
    utterance0 = np.array([frame00, frame01, frame02])

    freq100 = 9; freq101 = 7; freq102 = 9; freq103 = 3
    freq110 = 2; freq111 = 3; freq112 = 8; freq113 = 4
    frame10 = np.array([freq100, freq101, freq102, freq103])
    frame11 = np.array([freq110, freq111, freq112, freq113])
    utterance1 = np.array([frame10, frame11])

    freq200 = 6; freq201 = 2; freq202 = 6; freq203 = 4
    freq210 = 3; freq211 = 3; freq212 = 8; freq213 = 3
    freq220 = 2; freq221 = 7; freq222 = 9; freq223 = 5
    freq230 = 0; freq231 = 2; freq232 = 8; freq233 = 8
    frame20 = np.array([freq200, freq201, freq202, freq203])
    frame21 = np.array([freq210, freq211, freq212, freq213])
    frame22 = np.array([freq220, freq221, freq222, freq223])
    frame23 = np.array([freq230, freq231, freq232, freq233])
    utterance2 = np.array([frame20, frame21, frame22, frame23])

    # Create a NumPy array of objects to hold the utterances with different shapes
    spectrograms = np.array([utterance0, utterance1, utterance2], dtype=object)

    return spectrograms

def get_data_2():
    """
    This is the generating process from which example data 2 will derive

    Parameters:
    None

    Returns:
    numpy.ndarray: 1-d numpy array with 2-d numpy arrays as elements.
    """
    np.random.seed(0)
    recordings = np.random.randint(10)
    durations = [np.random.randint(low=5, high=10)
                 for i in range(recordings)]
    data = []
    k = 40 # Given as fixed constant
    for duration in durations:
        data.append(np.random.randint(10, size=(duration, k)))
    # data = np.asarray(data)
    return data

# get_data_1()

get_data_2()

[array([[3, 5, 2, 4, 7, 6, 8, 8, 1, 6, 7, 7, 8, 1, 5, 9, 8, 9, 4, 3, 0, 3,
         5, 0, 2, 3, 8, 1, 3, 3, 3, 7, 0, 1, 9, 9, 0, 4, 7, 3],
        [2, 7, 2, 0, 0, 4, 5, 5, 6, 8, 4, 1, 4, 9, 8, 1, 1, 7, 9, 9, 3, 6,
         7, 2, 0, 3, 5, 9, 4, 4, 6, 4, 4, 3, 4, 4, 8, 4, 3, 7],
        [5, 5, 0, 1, 5, 9, 3, 0, 5, 0, 1, 2, 4, 2, 0, 3, 2, 0, 7, 5, 9, 0,
         2, 7, 2, 9, 2, 3, 3, 2, 3, 4, 1, 2, 9, 1, 4, 6, 8, 2],
        [3, 0, 0, 6, 0, 6, 3, 3, 8, 8, 8, 2, 3, 2, 0, 8, 8, 3, 8, 2, 8, 4,
         3, 0, 4, 3, 6, 9, 8, 0, 8, 5, 9, 0, 9, 6, 5, 3, 1, 8],
        [0, 4, 9, 6, 5, 7, 8, 8, 9, 2, 8, 6, 6, 9, 1, 6, 8, 8, 3, 2, 3, 6,
         3, 6, 5, 7, 0, 8, 4, 6, 5, 8, 2, 3, 9, 7, 5, 3, 4, 5]]),
 array([[3, 3, 7, 9, 9, 9, 7, 3, 2, 3, 9, 7, 7, 5, 1, 2, 2, 8, 1, 5, 8, 4,
         0, 2, 5, 5, 0, 8, 1, 1, 0, 3, 8, 8, 4, 4, 0, 9, 3, 7],
        [3, 2, 1, 1, 2, 1, 4, 2, 5, 5, 5, 2, 5, 7, 7, 6, 1, 6, 7, 2, 3, 1,
         9, 5, 9, 9, 2, 0, 9, 1, 9, 0, 6, 0, 4, 8, 4, 3, 3, 8],
        [8, 7, 0, 3, 8, 7

#### **6.1. Slicing: Last Point**
Takes one 3-dimensional array with the length of the output instances. Your task is to keep only the $m$ last frames for each instance in the dataset.

To the extent that it is helpful, a formal description provided in the Appendix.

**Your Task:** Implement the function `slice_last_point`.

In [ ]:
import numpy as np
import torch

def get_data_1():
    """
    This is the generating process from which example data 1 will derive

    Parameters:
    None

    Returns:
    numpy.ndarray: 1-d numpy array with 2-d numpy arrays as elements.
    """
    freq000 = 3; freq001 = 1; freq002 = 4; freq003 = 1
    freq010 = 5; freq011 = 9; freq012 = 2; freq013 = 6
    freq020 = 5; freq021 = 3; freq022 = 5; freq023 = 8
    frame00 = np.array([freq000, freq001, freq002, freq003])
    frame01 = np.array([freq010, freq011, freq012, freq013])
    frame02 = np.array([freq020, freq021, freq022, freq023])
    utterance0 = np.array([frame00, frame01, frame02])

    freq100 = 9; freq101 = 7; freq102 = 9; freq103 = 3
    freq110 = 2; freq111 = 3; freq112 = 8; freq113 = 4
    frame10 = np.array([freq100, freq101, freq102, freq103])
    frame11 = np.array([freq110, freq111, freq112, freq113])
    utterance1 = np.array([frame10, frame11])

    freq200 = 6; freq201 = 6; freq202 = 6; freq203 = 4
    freq210 = 3; freq211 = 3; freq212 = 8; freq213 = 3
    freq220 = 2; freq221 = 7; freq222 = 9; freq223 = 5
    freq230 = 0; freq231 = 2; freq232 = 8; freq233 = 8
    frame20 = np.array([freq200, freq201, freq202, freq203])
    frame21 = np.array([freq210, freq211, freq212, freq213])
    frame22 = np.array([freq220, freq221, freq222, freq223])
    frame23 = np.array([freq230, freq231, freq232, freq233])
    utterance2 = np.array([frame20, frame21, frame22, frame23])

    # Create a NumPy array of objects to hold the utterances with different shapes
    spectrograms = np.array([utterance0, utterance1, utterance2], dtype=object)

    return spectrograms

def get_data_2():
    """
    This is the generating process from which example data 2 will derive

    Parameters:
    None

    Returns:
    numpy.ndarray: 1-d numpy array with 2-d numpy arrays as elements.
    """
    np.random.seed(0)
    # recordings = np.random.randint(10) # Original code generated a random number of recordings, which was causing issues with consistent output shapes. Changed to a fixed number for predictable testing.
    recordings = 3
    durations = [np.random.randint(low=5, high=10)
                 for i in range(recordings)]
    data = []
    k = 40 # Given as fixed constant
    for duration in durations:
        data.append(np.random.randint(10, size=(duration, k)))
    # data = np.asarray(data) # Original code commented this out. Need to convert list to numpy array.
    return np.array(data, dtype=object)

# get_data_1()

get_data_2()

array([array([[3, 7, 9, 3, 5, 2, 4, 7, 6, 8, 8, 1, 6, 7, 7, 8, 1, 5, 9, 8, 9, 4,
               3, 0, 3, 5, 0, 2, 3, 8, 1, 3, 3, 3, 7, 0, 1, 9, 9, 0],
              [4, 7, 3, 2, 7, 2, 0, 0, 4, 5, 5, 6, 8, 4, 1, 4, 9, 8, 1, 1, 7, 9,
               9, 3, 6, 7, 2, 0, 3, 5, 9, 4, 4, 6, 4, 4, 3, 4, 4, 8],
              [4, 3, 7, 5, 5, 0, 1, 5, 9, 3, 0, 5, 0, 1, 2, 4, 2, 0, 3, 2, 0, 7,
               5, 9, 0, 2, 7, 2, 9, 2, 3, 3, 2, 3, 4, 1, 2, 9, 1, 4],
              [6, 8, 2, 3, 0, 0, 6, 0, 6, 3, 3, 8, 8, 8, 2, 3, 2, 0, 8, 8, 3, 8,
               2, 8, 4, 3, 0, 4, 3, 6, 9, 8, 0, 8, 5, 9, 0, 9, 6, 5],
              [3, 1, 8, 0, 4, 9, 6, 5, 7, 8, 8, 9, 2, 8, 6, 6, 9, 1, 6, 8, 8, 3,
               2, 3, 6, 3, 6, 5, 7, 0, 8, 4, 6, 5, 8, 2, 3, 9, 7, 5],
              [3, 4, 5, 3, 3, 7, 9, 9, 9, 7, 3, 2, 3, 9, 7, 7, 5, 1, 2, 2, 8, 1,
               5, 8, 4, 0, 2, 5, 5, 0, 8, 1, 1, 0, 3, 8, 8, 4, 4, 0],
              [9, 3, 7, 3, 2, 1, 1, 2, 1, 4, 2, 5, 5, 5, 2, 5, 7, 7, 6, 1, 6, 7,
             

**Example 1**

In [ ]:
spectrograms = get_data_1()
duration = 2
print(slice_last_point(spectrograms, duration))

[[[5 9 2 6]
  [5 3 5 8]]

 [[9 7 9 3]
  [2 3 8 4]]

 [[2 7 9 5]
  [0 2 8 8]]]


**Expected Output 1**

<img src="images/ex3-1.png" width="600">

<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> slice_last_point(<br>spectrograms, duration) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[[5.&nbsp;9.&nbsp;2.&nbsp;6.] <br>
&nbsp;&nbsp;[5.&nbsp;3.&nbsp;5.&nbsp;8.]] <br>

&nbsp;[[9.&nbsp;7.&nbsp;9.&nbsp;3.] <br>
&nbsp;&nbsp;[2.&nbsp;3.&nbsp;8.&nbsp;4.]] <br>

&nbsp;[[2.&nbsp;7.&nbsp;9.&nbsp;5.] <br>
&nbsp;&nbsp;[0.&nbsp;2.&nbsp;8.&nbsp;8.]]] <br>
        </tt></td>
    </tr>
</table>

**Example 2**

In [ ]:
data = get_data_2()
m = 5
print(slice_last_point(data, m)[1])

[[4 1 7 6 9 4 1 5 9 7 1 3 5 7 3 6 6 7 9 1 9 6 0 3 8 4 1 4 5 0 3 1 4 4 4 0
  0 8 4 6]
 [9 3 3 2 1 2 1 3 4 1 1 0 7 8 4 3 5 6 3 2 9 8 1 4 0 8 3 9 5 5 1 7 8 6 4 7
  3 5 3 6]
 [4 7 3 0 5 9 3 7 5 5 8 0 8 3 6 9 3 2 7 0 3 0 3 6 1 9 2 9 4 9 1 3 2 4 9 7
  4 9 4 1]
 [2 7 2 3 9 7 6 6 2 3 6 0 8 0 7 6 5 9 6 5 2 7 1 9 2 2 5 6 4 2 2 1 0 9 0 2
  8 3 0 8]
 [8 1 0 5 8 2 3 5 3 8 6 4 6 3 6 2 6 5 5 9 4 6 5 1 3 3 8 9 5 5 6 0 9 7 5 1
  5 6 6 8]]


**Expected Output 2**:
<table style = "align:40%"  >
    <tr>
        <td style="text-align:left;"><tt><b> slice_last_point(<br>data, m)[1] </b></tt></td>
        <td style="text-align:left;"><tt>
[[7.&nbsp;2.&nbsp;7.&nbsp;1.&nbsp;6.&nbsp;5.&nbsp;0.&nbsp;0.&nbsp;3.&nbsp;1.&nbsp;9.&nbsp;9.&nbsp;6.&nbsp;6.&nbsp;7.&nbsp;8.&nbsp;8.&nbsp;7.&nbsp;0.&nbsp;8.&nbsp;6.&nbsp;8.&nbsp;9.&nbsp;8. <br>
&nbsp;&nbsp;3.&nbsp;6.&nbsp;1.&nbsp;7.&nbsp;4.&nbsp;9.&nbsp;2.&nbsp;0.&nbsp;8.&nbsp;2.&nbsp;7.&nbsp;8.&nbsp;4.&nbsp;4.&nbsp;1.&nbsp;7.] <br>
&nbsp;[6.&nbsp;9.&nbsp;4.&nbsp;1.&nbsp;5.&nbsp;9.&nbsp;7.&nbsp;1.&nbsp;3.&nbsp;5.&nbsp;7.&nbsp;3.&nbsp;6.&nbsp;6.&nbsp;7.&nbsp;9.&nbsp;1.&nbsp;9.&nbsp;6.&nbsp;0.&nbsp;3.&nbsp;8.&nbsp;4.&nbsp;1. <br>
&nbsp;&nbsp;4.&nbsp;5.&nbsp;0.&nbsp;3.&nbsp;1.&nbsp;4.&nbsp;4.&nbsp;4.&nbsp;0.&nbsp;0.&nbsp;8.&nbsp;4.&nbsp;6.&nbsp;9.&nbsp;3.&nbsp;3.] <br>
&nbsp;[2.&nbsp;1.&nbsp;2.&nbsp;1.&nbsp;3.&nbsp;4.&nbsp;1.&nbsp;1.&nbsp;0.&nbsp;7.&nbsp;8.&nbsp;4.&nbsp;3.&nbsp;5.&nbsp;6.&nbsp;3.&nbsp;2.&nbsp;9.&nbsp;8.&nbsp;1.&nbsp;4.&nbsp;0.&nbsp;8.&nbsp;3. <br>
&nbsp;&nbsp;9.&nbsp;5.&nbsp;5.&nbsp;1.&nbsp;7.&nbsp;8.&nbsp;6.&nbsp;4.&nbsp;7.&nbsp;3.&nbsp;5.&nbsp;3.&nbsp;6.&nbsp;4.&nbsp;7.&nbsp;3.] <br>
&nbsp;[0.&nbsp;5.&nbsp;9.&nbsp;3.&nbsp;7.&nbsp;5.&nbsp;5.&nbsp;8.&nbsp;0.&nbsp;8.&nbsp;3.&nbsp;6.&nbsp;9.&nbsp;3.&nbsp;2.&nbsp;7.&nbsp;0.&nbsp;3.&nbsp;0.&nbsp;3.&nbsp;6.&nbsp;1.&nbsp;9.&nbsp;2. <br>
&nbsp;&nbsp;9.&nbsp;4.&nbsp;9.&nbsp;1.&nbsp;3.&nbsp;2.&nbsp;4.&nbsp;9.&nbsp;7.&nbsp;4.&nbsp;9.&nbsp;4.&nbsp;1.&nbsp;2.&nbsp;7.&nbsp;2.] <br>
&nbsp;[3.&nbsp;9.&nbsp;7.&nbsp;6.&nbsp;6.&nbsp;2.&nbsp;3.&nbsp;6.&nbsp;0.&nbsp;8.&nbsp;0.&nbsp;7.&nbsp;6.&nbsp;5.&nbsp;9.&nbsp;6.&nbsp;5.&nbsp;2.&nbsp;7.&nbsp;1.&nbsp;9.&nbsp;2.&nbsp;2.&nbsp;5. <br>
&nbsp;&nbsp;6.&nbsp;4.&nbsp;2.&nbsp;2.&nbsp;1.&nbsp;0.&nbsp;9.&nbsp;0.&nbsp;2.&nbsp;8.&nbsp;3.&nbsp;0.&nbsp;8.&nbsp;8.&nbsp;1.&nbsp;0.]]
        </tt></td>
    </tr>
</table>

#### **6.2. Slicing: Fixed Point**
Takes one 3-dimensional array with the starting position and the length of the output instances. Your task is to slice the instances from the same starting position for the given length.

To the extent that it is helpful, a formal description provided in the Appendix.

**Your Task:** Implement the function `slice_fixed_point`.

In [ ]:
def slice_fixed_point(x, s, m):
    """
    Takes one 3-dimensional array with the starting position and the
    length of the output instances. Your task is to slice the instances
    from the same starting position for the given length.

    Parameters:
    x (numpy.ndarray): 1-d numpy array with 2-d numpy arrays as elements (n, ?, k).
    s (int): The starting reference index in dimension 2.
    m (int): The cutoff reference index in dimension 2.

    Returns:
    numpy.ndarray: A 3-dimensional int numpy array of shape (n, m-s, k)
    """
    spectrograms = x

    # Input function dimension specification
    assert(spectrograms.ndim == 1)
    for utter in spectrograms:
        assert(utter.ndim == 2)

    # Pre-define output function dimension specification
    dim1 = spectrograms.shape[0]     # n
    dim2 = m-s                      # m-s
    dim3 = spectrograms[0].shape[1]  # k

    result = np.zeros((dim1,dim2,dim3))

    #### Start of your code ####


    ####  End of your code  ####

    # Assert output function dimension specification
    assert(result.shape[0] == dim1)
    assert(result.shape[1] == dim2)
    assert(result.shape[2] == dim3)

    return result

**Test Example 1:**

In [ ]:
spectrograms = get_data_1()
start = 0
end = 2
print(slice_fixed_point(spectrograms, start, end))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


**Expected Output 1**

<img src="images/ex3-2.png" width="600">

<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> slice_fixed_point(<br>spectrograms, start, end) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[[3.&nbsp;1.&nbsp;4.&nbsp;1.] <br>
&nbsp;&nbsp;[5.&nbsp;9.&nbsp;2.&nbsp;6.]] <br>

&nbsp;[[9.&nbsp;7.&nbsp;9.&nbsp;3.] <br>
&nbsp;&nbsp;[2.&nbsp;3.&nbsp;8.&nbsp;4.]] <br>

&nbsp;[[6.&nbsp;2.&nbsp;6.&nbsp;4.] <br>
&nbsp;&nbsp;[3.&nbsp;3.&nbsp;8.&nbsp;3.]]] <br>
        </tt></td>
    </tr>
</table>

**Test Example 2:**

In [ ]:
data = get_data_2()
s = 2
m = 5
print(slice_fixed_point(data, s, m)[1])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Expected Output 2**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> slice_fixed_point(<br>data, s, m)[1] </b></tt></td>
        <td style="text-align:left;"><tt>
[[8.&nbsp;7.&nbsp;0.&nbsp;3.&nbsp;8.&nbsp;7.&nbsp;7.&nbsp;1.&nbsp;8.&nbsp;4.&nbsp;7.&nbsp;0.&nbsp;4.&nbsp;9.&nbsp;0.&nbsp;6.&nbsp;4.&nbsp;2.&nbsp;4.&nbsp;6.&nbsp;3.&nbsp;3.&nbsp;7.&nbsp;8. <br>
&nbsp;&nbsp;5.&nbsp;0.&nbsp;8.&nbsp;5.&nbsp;4.&nbsp;7.&nbsp;4.&nbsp;1.&nbsp;3.&nbsp;3.&nbsp;9.&nbsp;2.&nbsp;5.&nbsp;2.&nbsp;3.&nbsp;5.] <br>
&nbsp;[7.&nbsp;2.&nbsp;7.&nbsp;1.&nbsp;6.&nbsp;5.&nbsp;0.&nbsp;0.&nbsp;3.&nbsp;1.&nbsp;9.&nbsp;9.&nbsp;6.&nbsp;6.&nbsp;7.&nbsp;8.&nbsp;8.&nbsp;7.&nbsp;0.&nbsp;8.&nbsp;6.&nbsp;8.&nbsp;9.&nbsp;8. <br>
&nbsp;&nbsp;3.&nbsp;6.&nbsp;1.&nbsp;7.&nbsp;4.&nbsp;9.&nbsp;2.&nbsp;0.&nbsp;8.&nbsp;2.&nbsp;7.&nbsp;8.&nbsp;4.&nbsp;4.&nbsp;1.&nbsp;7.] <br>
&nbsp;[6.&nbsp;9.&nbsp;4.&nbsp;1.&nbsp;5.&nbsp;9.&nbsp;7.&nbsp;1.&nbsp;3.&nbsp;5.&nbsp;7.&nbsp;3.&nbsp;6.&nbsp;6.&nbsp;7.&nbsp;9.&nbsp;1.&nbsp;9.&nbsp;6.&nbsp;0.&nbsp;3.&nbsp;8.&nbsp;4.&nbsp;1. <br>
&nbsp;&nbsp;4.&nbsp;5.&nbsp;0.&nbsp;3.&nbsp;1.&nbsp;4.&nbsp;4.&nbsp;4.&nbsp;0.&nbsp;0.&nbsp;8.&nbsp;4.&nbsp;6.&nbsp;9.&nbsp;3.&nbsp;3.]]
        </tt></td>
    </tr>
</table>

#### **6.3. Slicing: Random Point**
Takes one 3-dimensional array with the length of the output instances. Your task is to slice the instances from a random point in each of the utterances with the given length. Please use function `numpy.random.randint` for generating the starting position.

To the extent that it is helpful, a formal description provided in the Appendix.

**Your Task:** Implement the function `slice_random_point`.

In [ ]:
def slice_random_point(x, d):
    """
    Takes one 3-dimensional array with the length of the output instances.
    Your task is to slice the instances from a random point in each of the
    utterances with the given length. Please use offset and refer to their
    mathematical correspondance.

    Parameters:
    x (numpy.ndarray): 1-d numpy array with 2-d numpy arrays as elements (n, ?, k).
    d (int): The resulting size of the data in dimension 2.

    Returns:
    numpy.ndarray: A 3-dimensional int numpy array of shape (n, d, k)
    """
    spectrograms = x

    # Input function dimension specification
    assert(spectrograms.ndim == 1)
    for utter in spectrograms:
        assert(utter.ndim == 2)
        assert(utter.shape[0] >= d)

    offset = [np.random.randint(utter.shape[0]-d+1)
              if utter.shape[0]-d > 0 else 0
              for utter in spectrograms]

    # Pre-define output function dimension specification
    dim1 = spectrograms.shape[0]    # n
    dim2 = d                       # d
    dim3 = spectrograms[0].shape[1] # k

    result = np.zeros((dim1,dim2,dim3))

    #### Start of your code ####




    ####  End of your code  ####

    # Assert output function dimension specification
    assert(result.shape[0] == dim1)
    assert(result.shape[1] == dim2)
    assert(result.shape[2] == dim3)

    return result

##### Test Example 1:

In [ ]:
np.random.seed(1)
spectrograms = get_data_1()
duration = 2
print(slice_random_point(spectrograms, duration))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


##### Expected Output 1

<img src="images/ex3-3.png" width="600">

<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> slice_random_point(<br>spectrograms, duration) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[[5.&nbsp;9.&nbsp;2.&nbsp;6.] <br>
&nbsp;&nbsp;[5.&nbsp;3.&nbsp;5.&nbsp;8.]] <br>

&nbsp;[[9.&nbsp;7.&nbsp;9.&nbsp;3.] <br>
&nbsp;&nbsp;[2.&nbsp;3.&nbsp;8.&nbsp;4.]] <br>

&nbsp;[[6.&nbsp;2.&nbsp;6.&nbsp;4.] <br>
&nbsp;&nbsp;[3.&nbsp;3.&nbsp;8.&nbsp;3.]]] <br>
        </tt></td>
    </tr>
</table>

##### Test Example 2:

In [ ]:
data = get_data_2()
d = 4
print(slice_random_point(data, d)[1])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Expected Output 2**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> slice_random_point(<br>data, d)[1] </b></tt></td>
        <td style="text-align:left;"><tt>
[[3.&nbsp;3.&nbsp;7.&nbsp;9.&nbsp;9.&nbsp;9.&nbsp;7.&nbsp;3.&nbsp;2.&nbsp;3.&nbsp;9.&nbsp;7.&nbsp;7.&nbsp;5.&nbsp;1.&nbsp;2.&nbsp;2.&nbsp;8.&nbsp;1.&nbsp;5.&nbsp;8.&nbsp;4.&nbsp;0.&nbsp;2. <br>
&nbsp;&nbsp;5.&nbsp;5.&nbsp;0.&nbsp;8.&nbsp;1.&nbsp;1.&nbsp;0.&nbsp;3.&nbsp;8.&nbsp;8.&nbsp;4.&nbsp;4.&nbsp;0.&nbsp;9.&nbsp;3.&nbsp;7.] <br>
&nbsp;[3.&nbsp;2.&nbsp;1.&nbsp;1.&nbsp;2.&nbsp;1.&nbsp;4.&nbsp;2.&nbsp;5.&nbsp;5.&nbsp;5.&nbsp;2.&nbsp;5.&nbsp;7.&nbsp;7.&nbsp;6.&nbsp;1.&nbsp;6.&nbsp;7.&nbsp;2.&nbsp;3.&nbsp;1.&nbsp;9.&nbsp;5. <br>
&nbsp;&nbsp;9.&nbsp;9.&nbsp;2.&nbsp;0.&nbsp;9.&nbsp;1.&nbsp;9.&nbsp;0.&nbsp;6.&nbsp;0.&nbsp;4.&nbsp;8.&nbsp;4.&nbsp;3.&nbsp;3.&nbsp;8.] <br>
&nbsp;[8.&nbsp;7.&nbsp;0.&nbsp;3.&nbsp;8.&nbsp;7.&nbsp;7.&nbsp;1.&nbsp;8.&nbsp;4.&nbsp;7.&nbsp;0.&nbsp;4.&nbsp;9.&nbsp;0.&nbsp;6.&nbsp;4.&nbsp;2.&nbsp;4.&nbsp;6.&nbsp;3.&nbsp;3.&nbsp;7.&nbsp;8. <br>
&nbsp;&nbsp;5.&nbsp;0.&nbsp;8.&nbsp;5.&nbsp;4.&nbsp;7.&nbsp;4.&nbsp;1.&nbsp;3.&nbsp;3.&nbsp;9.&nbsp;2.&nbsp;5.&nbsp;2.&nbsp;3.&nbsp;5.] <br>
&nbsp;[7.&nbsp;2.&nbsp;7.&nbsp;1.&nbsp;6.&nbsp;5.&nbsp;0.&nbsp;0.&nbsp;3.&nbsp;1.&nbsp;9.&nbsp;9.&nbsp;6.&nbsp;6.&nbsp;7.&nbsp;8.&nbsp;8.&nbsp;7.&nbsp;0.&nbsp;8.&nbsp;6.&nbsp;8.&nbsp;9.&nbsp;8. <br>
&nbsp;&nbsp;3.&nbsp;6.&nbsp;1.&nbsp;7.&nbsp;4.&nbsp;9.&nbsp;2.&nbsp;0.&nbsp;8.&nbsp;2.&nbsp;7.&nbsp;8.&nbsp;4.&nbsp;4.&nbsp;1.&nbsp;7.]]
        </tt></td>
    </tr>
</table>

---

#### **6.4. Padding: Ending Pattern**
Takes one 3-dimensional array. Your task is to pad the instances from the end position as shown in the example below. That is, you need to pad the reflection of the utterance mirrored along the edge values of the array.

To the extent that it is helpful, a formal description provided in the Appendix.

**Your Task:** Implement the function `pad_ending_pattern`.

In [ ]:
def pad_ending_pattern(x):
    """
    Takes one 3-dimensional array. Your task is to pad the instances from
    the end position as shown in the example below. That is, you need to
    pads with the reflection of the vector mirrored along the edge of the array.

    Parameters:
    x (numpy.ndarray): 1-d numpy array with 2-d numpy arrays as elements.

    Returns:
    numpy.ndarray: 3-dimensional int numpy array
    """
    spectrograms = x

    # Input function dimension specification
    assert(spectrograms.ndim == 1)
    for utter in spectrograms:
        assert(utter.ndim == 2)

    # Pre-define output function dimension specification
    dim1 = spectrograms.shape[0]    # n
    dim2 = max([utter.shape[0] for utter in spectrograms]) # m
    dim3 = spectrograms[0].shape[1] # k

    result = np.zeros((dim1, dim2, dim3))

    #### Start of your code ####



    ####  End of your code  ####

    # Assert output function dimension specification
    assert(result.shape[0] == dim1)
    assert(result.shape[1] == dim2)
    assert(result.shape[2] == dim3)

    return result

**Test Example 1:**

In [ ]:
spectrograms = get_data_1()
duration = 2
print(pad_ending_pattern(spectrograms))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
